version: "3.7"

services:
  app:
    build: .
    container_name: django-gunicorn
    restart: always
    env_file:
      - django.env
    deploy:
      resources:
        reservations:
          memory: 6G
    ports:
      - "8000:8000"
    command:
      "gunicorn -c prestart.py --workers=2 --threads 3 -t 30 --bind=0.0.0.0:8000 Sprint.wsgi:application --preload"

  nginx:
    build: nginx
    container_name: ngx
    ports:
      - "80:80"
    depends_on:
      - app