name: Sprint
channels:
  - conda-forge
  - defaults
dependencies:
  - uwsgi
  - apscheduler=3.6.3
  - django=3.0.3
  - et_xmlfile=1.0.1
  - gensim=3.8.3
  - jinja2=2.11.2
  - jpype1=0.7.5
  - numpy=1.18.1
  - pip=20.0.2
  - python=3.7.7
  - readline=8.0
  - requests=2.23.0
  - setuptools=47.1.1
  - sqlalchemy=1.3.17
  - sqlite=3.31.1
  - zlib=1.2.11
  - pip:
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - cython==0.29.19
    - lxml==4.5.1
    - owlready2==0.24
    - pillow==7.1.2
    - pygments==2.6.1
    - pyparsing==2.4.7
    - pypdf2==1.26.0
    - rdflib==5.0.0
    - reportlab==3.5.42
    - simplejson==3.17.0
    - termcolor==1.1.0
    - z3c-rml==3.10.0
    - zope-event==4.4
    - zope-interface==5.1.0
    - zope-schema==6.0.0

