name: Sprint
channels:
  - conda-forge
  - defaults
dependencies:
  - apscheduler=3.6.3
  - asgiref=3.2.7
  - blas=1.0
  - boto=2.49.0
  - boto3=1.9.66
  - botocore=1.12.189
  - ca-certificates=2020.6.20
  - cachetools=3.1.1
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - cryptography=2.9.2
  - django=3.0.3
  - docutils=0.16
  - et_xmlfile=1.0.1
  - gensim=3.8.3
  - google-api-core=1.17.0
  - google-auth=1.14.1
  - google-cloud-core=1.3.0
  - google-cloud-storage=1.28.0
  - google-resumable-media=0.5.0
  - googleapis-common-protos=1.51.0
  - idna=2.9
  - intel-openmp=2019.4
  - jdcal=1.4.1
  - jinja2=2.11.2
  - jmespath=0.9.4
  - jpype1=0.7.5
  - libcxx=10.0.0
  - libedit=3.1.20181209
  - libffi=3.3
  - libprotobuf=3.11.4
  - markupsafe=1.1.1
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.1
  - ncurses=6.2
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openpyxl=3.0.3
  - openssl=1.1.1g
  - pandas=1.0.3
  - pip=20.0.2
  - protobuf=3.11.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pyopenssl=19.1.0
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - readline=8.0
  - requests=2.23.0
  - rsa=4.0
  - s3transfer=0.1.13
  - scipy=1.4.1
  - setuptools=47.1.1
  - six=1.14.0
  - smart_open=2.0.0
  - sqlalchemy=1.3.17
  - sqlite=3.31.1
  - sqlparse=0.3.1
  - tk=8.6.8
  - tzlocal=2.1
  - urllib3=1.25.8
  - wheel=0.34.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - backports-tempfile==1.0
    - backports-weakref==1.0.post1
    - cython==0.29.19
    - isodate==0.6.0
    - lxml==4.5.1
    - owlready2==0.24
    - pillow==7.1.2
    - pygments==2.6.1
    - pyparsing==2.4.7
    - pypdf2==1.26.0
    - rdflib==5.0.0
    - reportlab==3.5.42
    - simplejson==3.17.0
    - termcolor==1.1.0
    - z3c-rml==3.10.0
    - zope-event==4.4
    - zope-interface==5.1.0
    - zope-schema==6.0.0
    - libgfortran==3.0.1

